services:
  # A Docker web service
  - type: web
    name: Ngrok
    env: docker
    repo: https://github.com/AkashiCoin/Railway-Ngrok.git # optional
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
      - key: 2QUXIIUdLkIgvcNRMqo0ZxbMfPm_3HhAjwewpfC2qFRh5Vpiv
        sync: false
      - key: jp
        sync: false
